agent:
  mock: true
  interceptMethod: XXX.XXX.XXX.class#method(args)
  rebaseMethod: XXX.XXX.XXX.class#method(args)
  infoObject: XXX.XXX.class#field
database:
  url: jdbc:mysql://localhost:3306/mydb
  username: myuser
  password: mypassword
